### ISSUE TITLE
Test Item #2

### ISSUE THREAD

**Issue by chrisyeong** [creditera/PMISTestRepo#2]
#### Summary: 

Creating a test item here to see if the webhook is being picked up by Slack. Also using Markdown to format to make this issue look semi-pretty.

#### Steps:

1. Create an issue
2. Take a look at the #test Slack channel

#### Expected results:

You should see your item created in Slack

#### Actual results:

Hope this worked?

**Comment by lewchrist** [comment]
This seems to be working.....
